apiVersion: batch/v1
kind: Job
metadata:
  namespace: example02
  name: my-db-upgrade
  annotations:
#     argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-100"
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "30"
      restartPolicy: Never
  backoffLimit: 2    
